development:
  adapter: mysql2
  encoding: utf8
  database: open_food_network_dev
  pool: 5
  host: localhost
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

test:
  adapter: mysql2
  encoding: utf8
  database: open_food_network_test<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 5
  host: localhost
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

#not used with heroku
production:
  adapter: mysql2
  encoding: utf8
  database: open_food_network_prod
  pool: 5
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

staging:
  adapter: mysql2
  encoding: utf8
  database: open_food_network_prod
  pool: 5
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
